import type { DashboardOverview, TradeHistoryResponse, TraderProfileContext } from './types'
import type { ShibuyaSamplePreview } from './runtime'

// Sample data used to teach the workflow before a trader has live account data.
export const SAMPLE_WORKSPACE_DATA = {
  overview: {
    access_tier: 'sample',
    billing_status: 'sample',
    offer_kind: 'sample',
    case_status: 'sample_preview',
    trader_mode: 'retail_fn0_struggler' as const,
    next_action: 'Upload next meaningful session',
    days_left: null,
    access_expires_at: null,
    data_source: 'sample_dataset',
    guided_review_included: false,
    guided_review_status: null,
    guided_review_booked_at: null,
    guided_review_completed_at: null,
    guided_review_url: null,
    profile_completed: true,
    upload_count: 2,
    uploads_used: 2,
    upload_limit: null,
    uploads_remaining: null,
    latest_upload_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    reports_ready: 1,
    latest_report_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    last_report_snapshot_id: 'sample-upload-2',
    analysis_summary: {
      state: 'under_pressure' as const,
      recovery_ladder: 'under_pressure' as const,
      current_enemy: 'Overtrading is the main leak taxing the account right now.',
      edge_verdict: 'Edge is present, but behavior is still taxing it.',
      adherence_verdict: 'Standards are slipping. Tighten the loop before the leak compounds.',
      conviction_posture: 'Conviction is being wasted on too many decisions.',
      risk_ruin_posture: 'Ruin pressure is visible. One uncontrolled sequence can still do serious damage.',
      drift_posture: 'Drift is improving, but only if the next upload confirms it.',
      next_session_command: 'Trade fewer times and only from the first clean setup that actually deserves risk.',
      what_to_protect: [
        'Protect capital runway before you try to make the session exciting.',
        'Protect the process that already produced positive net P&L.',
        'Protect yourself from expiry-day size creep and zero-to-hero impulses.',
      ],
    },
    daily_briefing: {
      date: new Date().toISOString().slice(0, 10),
      current_state: 'under_pressure' as const,
      current_risk: 'overtrading' as const,
      avoid_today: 'Overtrading is the main leak taxing the account right now.',
      mission_line: 'Trade fewer times and only from the first clean setup that actually deserves risk.',
      headline: 'Lock the mission before the first order.',
      summary: 'Protect capital runway before you try to make the session exciting.',
      action_plan: [
        'Trade fewer times and only from the first clean setup that actually deserves risk.',
        'Protect capital runway before you try to make the session exciting.',
        'Upload the next meaningful session quickly so the proof loop stays honest.',
      ],
      proof_focus: 'Recover the next slice of discipline leak from 8100 worth of avoidable damage.',
      trader_mode: 'retail_fn0_struggler' as const,
      completed_at: new Date().toISOString(),
    },
    daily_debrief: {
      date: new Date().toISOString().slice(0, 10),
      gate_obeyed: true,
      stopped_correctly: true,
      protected_capital: true,
      main_lapse: 'Took one unnecessary expiry-day chase after the best move was gone.',
      main_win: 'Did not attempt to win the day back after the first red sequence.',
      tomorrow_line: 'Trade less, trade cleaner, and stop after the first reactive impulse.',
      standards_held_today: ['Capital preserved', 'Stop respected'],
      standards_broken_today: ['Overtrading'],
      completed_at: new Date().toISOString(),
    },
    saved_capital_vs_baseline: 2700,
    loss_quality: 'leaking_discipline',
    standards_adherence: 72,
    recurring_enemy: 'overtrading',
    recovery_ladder: 'under_pressure' as const,
    review_eligibility: false,
    review_summary: {
      eligible: false,
      touchpoint_1_status: 'locked',
      touchpoint_2_status: 'locked',
      next_review_type: 'kickoff_review',
      upcoming_appointment_at: null,
    },
    support_summary: {
      open_count: 0,
      latest_ticket_id: null,
      latest_status: null,
      latest_priority: null,
      latest_subject: null,
    },
    artifact_descriptors: [
      {
        kind: 'baseline_report',
        label: 'Baseline Brief',
        report_id: 'sample-report-baseline',
        snapshot_id: 'sample-upload-1',
        available: true,
      },
      {
        kind: 'latest_report',
        label: 'Latest Progress Brief',
        report_id: 'sample-report-latest',
        snapshot_id: 'sample-upload-2',
        available: true,
      },
      {
        kind: 'delta_report',
        label: 'Baseline vs Latest Delta',
        report_id: 'sample-report-latest',
        snapshot_id: 'sample-upload-2',
        available: true,
      },
    ],
    standards_held_today: ['Capital preserved', 'Stop respected'],
    standards_broken_today: ['Overtrading'],
    // Sample operating signals only; live values must come from generated backend artifacts.
    bql_state: 'MEDIOCRE',
    bql_score: 0.58,
    monte_carlo_drift: 8920,
    ruin_probability: 0.034,
    discipline_tax_30d: 8100,
    discipline_tax_breakdown: {
      revenge_trades: 4200,
      overtrading: 2350,
      size_violations: 1550,
    },
    sharpe_scenario: 1.67,
    pnl_gross: 30810, // Sum of all winning trades
    pnl_net: 22710, // Gross minus discipline tax (30810 - 8100)
    total_trades: 30,
    winning_trades: 20,
    // Sample edge portfolio used to explain the workflow.
    edge_portfolio: [
      { 
        name: 'Nifty opening drive', 
        status: 'PRIME' as const, 
        win_rate: 71, 
        pnl: 12300,
        trades: 12,
        avg_rr: 2.1,
        action: 'Sample scenario: this is the cleanest edge in the demo account. In live mode, this language must come from uploaded trade history and generated artifacts.' 
      },
      { 
        name: 'BankNifty reversal fade', 
        status: 'STABLE' as const, 
        win_rate: 58, 
        pnl: 8900,
        trades: 10,
        avg_rr: 1.4,
        action: 'Sample scenario: this setup still works in the demo account, but only when the first move exhausts itself. Live mode must prove this from account history.' 
      },
      { 
        name: 'Expiry-day breakout chase', 
        status: 'DECAYED' as const, 
        win_rate: 39, 
        pnl: -6400,
        trades: 8,
        avg_rr: 0.8,
        action: 'Sample scenario: this setup is intentionally marked as a leak so the workflow can demonstrate what a stop-trading mandate looks like.' 
      },
    ],
    // Recent costly mistakes with specific details
    recent_errors: [
      { date: '2025-11-28', pair: 'BANKNIFTY', error: 'Revenge trade after the first expiry loss', cost: 520 },
      { date: '2025-11-25', pair: 'NIFTY', error: 'Doubled size into a losing options chase', cost: 380 },
      { date: '2025-11-22', pair: 'RELIANCE', error: '4th trade in 90min after the best move was already gone', cost: 290 },
    ],
    loyalty_unlock: {
      month: 2,
      reward: 'Premium reset review',
      message: 'Complete 30 more disciplined days and unlock a deeper reset review on the next cycle.',
      progress_pct: 67,
    },
    next_coach_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    streak: {
      current: 4,
      best: 12,
      message: '4-day discipline streak. Your best was 12 days (Oct 3-15).',
    },
  },
  alerts: {
    alerts: [
      { 
        id: '1', 
        type: 'crucial_moment' as const, 
        title: 'Sample alert: revenge pattern candidate',
        body: 'Sample scenario: after the first BankNifty expiry loss, the demo account takes three more trades in 47 minutes. The point is the workflow, not a live account finding.',
        severity: 'high' as const, 
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), 
        acknowledged: false,
        trade_ids: ['T-1847', 'T-1848', 'T-1849'],
      },
      { 
        id: '2', 
        type: 'margin_of_safety' as const, 
        title: 'Sample weekly margin-of-safety brief',
        body: 'Your MoS improved from 1.2R to 1.8R this week. Main driver: you stopped forcing late index-option trades after the morning edge was already gone.',
        severity: 'info' as const, 
        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), 
        acknowledged: false,
      },
      { 
        id: '3', 
        type: 'slump_warning' as const, 
        title: 'Sample Wednesday blowup review',
        body: 'Sample scenario: Wednesday losses are intentionally elevated so the demo can show how Shibuya turns a bad session into a next-session guardrail.',
        severity: 'medium' as const, 
        timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(), 
        acknowledged: true,
      },
      { 
        id: '4', 
        type: 'crucial_moment' as const, 
        title: 'Sample protected-edge reminder',
        body: 'Sample scenario: the Nifty opening drive is the cleanest demo setup. In live mode, this claim must come from uploaded account history.',
        severity: 'medium' as const, 
        timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(), 
        acknowledged: false,
      },
      { 
        id: '5', 
        type: 'info' as const, 
        title: 'Sample edge portfolio update',
        body: 'BankNifty reversal fade has been upgraded from DECAYED to STABLE after 8 consecutive positive weeks. Resume with small size, not hero size.',
        severity: 'low' as const, 
        timestamp: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(), 
        acknowledged: true,
      },
    ],
    unread_count: 3,
  },
  edgePortfolio: {
    edges: [
      { 
        name: 'Nifty opening drive', 
        status: 'PRIME' as const, 
        win_rate: 71,
        pnl: 42300,
        trades: 34,
        avg_rr: 2.1,
        expectancy: 0.89,
        sharpe: 2.3,
        max_dd_pct: 3.2,
        best_month: 'October (+21400 sample units)',
        action: 'Sample action: this is the cleanest edge in the demo account. In live mode, this language must come from uploaded trade history.' 
      },
      { 
        name: 'BankNifty reversal fade', 
        status: 'STABLE' as const, 
        win_rate: 58,
        pnl: 18900,
        trades: 41,
        avg_rr: 1.4,
        expectancy: 0.34,
        sharpe: 1.4,
        max_dd_pct: 5.1,
        best_month: 'September (+8900 sample units)',
        action: 'Sample action: keep trading it only after the first move exhausts itself. Live mode must prove this from account history.' 
      },
      { 
        name: 'Expiry-day breakout chase', 
        status: 'DECAYED' as const, 
        win_rate: 39,
        pnl: -16400,
        trades: 28,
        avg_rr: 0.8,
        expectancy: -0.42,
        sharpe: -0.8,
        max_dd_pct: 12.3,
        best_month: 'None (negative all 3 months)',
        action: 'Sample action: stop immediately. This setup is intentionally marked as a leak so the workflow can show a stop-trading mandate.' 
      },
      { 
        name: 'Options scalp around VWAP', 
        status: 'STABLE' as const, 
        win_rate: 52,
        pnl: 7200,
        trades: 12,
        avg_rr: 1.9,
        expectancy: 0.21,
        sharpe: 1.1,
        max_dd_pct: 4.8,
        best_month: 'November (+4800 sample units)',
        action: 'Sample action: promising but unproven. In live mode, keep size small until the trader account has enough examples.' 
      },
      { 
        name: 'Friday overtrade spiral', 
        status: 'DECAYED' as const, 
        win_rate: 44,
        pnl: -8900,
        trades: 32,
        avg_rr: 0.6,
        expectancy: -0.28,
        sharpe: -0.5,
        max_dd_pct: 8.7,
        best_month: 'None',
        action: 'Sample action: Friday afternoon is the demo account overtrade window. Cut it after the edge is gone.' 
      },
    ],
    summary: {
      total: 5,
      prime: 1,
      decayed: 2,
      stable: 2,
      total_pnl: 43100,
      recommendation: 'Your portfolio is unbalanced. Most of your gains come from the Nifty opening drive. Kill the expiry-day chase and the Friday overtrade spiral now. If you only trade PRIME + STABLE edges at proper size, your monthly trajectory improves sharply.',
    },
  },
  slump: {
    is_slump: true,
    bql_state: 'EMOTIONAL_TRAINWRECK',
    consecutive_losses: 7,
    drawdown_pct: 8.4,
    days_in_slump: 3,
    prescription: {
      message: 'Sample scenario: the demo account is in a slump state. In live mode, this prescription requires uploaded account history and generated backend evidence.',
      max_trades_per_session: 2,
      banned_assets: ['BANKNIFTY weeklys', 'MIDCPNIFTY', 'FINNIFTY'],
      position_cap_pct: 25,
      cooldown_hours: 4,
      rules: [
        'Maximum 2 trades per session (you averaged 6.3 during this slump)',
        'Position size capped at 25% of your normal size',
        'No trading BankNifty weeklys, MIDCPNIFTY, or FINNIFTY. These are your tilt instruments right now.',
        'Mandatory 4-hour cooldown between sessions',
        'Must journal BEFORE placing any trade (screenshot required)',
        'If the demo account hits its daily loss limit, it is done for 48 hours.',
      ],
      recovery_criteria: [
        '3 consecutive winning trades OR',
        '2 days with positive PnL OR',
        'BQL score returns below 0.50',
      ],
      historical_context: 'Sample scenario only. Live historical context must come from the trader account and should not imply population-wide recovery guarantees.',
    },
  },
  shadowBoxing: {
    simulations: [
      { 
        firm: 'Aggressive 10% Rulebook', 
        account_size: 100000, 
        profit_target_pct: 10, 
        max_dd_pct: 10, 
        your_pnl_pct: 7.8, 
        your_max_dd_pct: 6.2, 
        passed: false, 
        pass_probability: 0.68,
        failure_reason: 'Missed profit target by 2.2%',
        improvement_needed: 'At current pace, need 8 more trading days to hit target',
      },
      { 
        firm: 'Lean 10% Rulebook', 
        account_size: 50000, 
        profit_target_pct: 10, 
        max_dd_pct: 10, 
        your_pnl_pct: 7.8, 
        your_max_dd_pct: 6.2, 
        passed: false, 
        pass_probability: 0.74,
        failure_reason: 'Missed profit target by 2.2%',
        improvement_needed: 'Smaller account = less pressure. Higher pass rate.',
      },
      { 
        firm: 'Low-DD Evaluation', 
        account_size: 100000, 
        profit_target_pct: 6, 
        max_dd_pct: 4, 
        your_pnl_pct: 7.8, 
        your_max_dd_pct: 6.2, 
        passed: false, 
        pass_probability: 0.42,
        failure_reason: 'Max DD exceeded (6.2% vs 4% limit)',
        improvement_needed: 'Need to reduce position sizing by 35% for this firm',
      },
      { 
        firm: 'Fast Track 8%', 
        account_size: 200000, 
        profit_target_pct: 8, 
        max_dd_pct: 8, 
        your_pnl_pct: 7.8, 
        your_max_dd_pct: 6.2, 
        passed: false, 
        pass_probability: 0.71,
        failure_reason: 'Missed profit target by 0.2%',
        improvement_needed: '2 more winning trades would have passed',
      },
      { 
        firm: 'Flexible 5% Target', 
        account_size: 100000, 
        profit_target_pct: 5, 
        max_dd_pct: 10, 
        your_pnl_pct: 7.8, 
        your_max_dd_pct: 6.2, 
        passed: true, 
        pass_probability: 0.89,
        days_to_pass: 18,
        buffer: '+2.8% above target',
      },
      { 
        firm: 'Standard 8% Target', 
        account_size: 100000, 
        profit_target_pct: 8, 
        max_dd_pct: 8, 
        your_pnl_pct: 7.8, 
        your_max_dd_pct: 6.2, 
        passed: false, 
        pass_probability: 0.67,
        failure_reason: 'Missed profit target by 0.2%',
        improvement_needed: 'Very close. One more trading week likely passes.',
      },
    ],
    best_result: { 
      firm: 'Flexible 5% Target', 
      account_size: 100000, 
      profit_target_pct: 5, 
      max_dd_pct: 10, 
      your_pnl_pct: 7.8, 
      your_max_dd_pct: 6.2, 
      passed: true, 
      pass_probability: 0.89,
      days_to_pass: 18,
      buffer: '+2.8% above target',
    },
    message: 'You passed 1 out of 6 funded-account rulebooks with your current trading. Flexible 5% Target is your best match right now. The stricter 10% and low-drawdown rulebooks still punish your drawdown control more than your raw edge.',
    capital_ready_score: 62,
    capital_ready_breakdown: {
      consistency: 71,
      drawdown_control: 58,
      profit_factor: 1.8,
      recommendation: 'Sample scenario: funded-account readiness is limited by drawdown control. Treat this as workflow illustration, not a pass prediction.',
    },
  },
  reports: {
    status: 'success',
    count: 2,
    reports: [
      {
        id: 'sample-report-1',
        name: 'Baseline Reset Brief',
        discipline_score: 58,
        emotional_cost: 8100,
        primary_pattern: 'Revenge trading remains the main leak after index-option losses.',
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'sample-report-2',
        name: 'Premium Reset Review',
        discipline_score: 64,
        emotional_cost: 5400,
        primary_pattern: 'Overtrading pressure improved after the last mandate, but expiry-day size creep remains open.',
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  comparison: {
    has_comparison: true,
    last_report_snapshot_id: 'sample-upload-2',
    baseline: {
      snapshot_id: 'sample-upload-1',
      upload_id: 'sample-upload-1',
      captured_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      discipline_tax: 8100,
      discipline_tax_breakdown: {
        revenge_trades: 4200,
        overtrading: 2350,
        size_violations: 1550,
      },
      bql_score: 0.66,
      bql_state: 'MEDIOCRE',
      pnl_net: 18200,
      pnl_gross: 26300,
      total_trades: 24,
      winning_trades: 14,
      ruin_probability: 0.051,
      behavior_share: 0.308,
      breach_risk_score: 63.2,
      primary_pattern: 'revenge trades',
    },
    latest: {
      snapshot_id: 'sample-upload-2',
      upload_id: 'sample-upload-2',
      captured_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      discipline_tax: 5400,
      discipline_tax_breakdown: {
        revenge_trades: 2100,
        overtrading: 1900,
        size_violations: 1400,
      },
      bql_score: 0.52,
      bql_state: 'COMPOSURE_RETURNING',
      pnl_net: 22710,
      pnl_gross: 28110,
      total_trades: 30,
      winning_trades: 20,
      ruin_probability: 0.034,
      behavior_share: 0.192,
      breach_risk_score: 49.6,
      primary_pattern: 'overtrading',
    },
    delta_summary: {
      discipline_tax_change: -2700,
      revenge_change: -2100,
      overtrading_change: -450,
      size_change: -150,
      edge_vs_behavior_shift: 'behavior improving',
      breach_risk_shift: 'risk improving',
      bql_change: -0.14,
    },
  },
  tradeHistory: {
    trades: [
      { id: 'T-1001', timestamp: '2025-12-02T04:12:00Z', exit_time: '2025-12-02T04:35:00Z', symbol: 'NIFTY24DEC22500CE', side: 'BUY' as const, size: 2, pnl: 4520, bds_at_time: 0.32 },
      { id: 'T-1002', timestamp: '2025-12-02T05:05:00Z', exit_time: '2025-12-02T05:22:00Z', symbol: 'BANKNIFTY24DEC48000PE', side: 'SELL' as const, size: 1, pnl: -2180, bds_at_time: 0.64 },
      { id: 'T-1003', timestamp: '2025-12-02T05:45:00Z', exit_time: '2025-12-02T06:10:00Z', symbol: 'NIFTY24DEC22400PE', side: 'BUY' as const, size: 2, pnl: 3810, bds_at_time: 0.28 },
      { id: 'T-1004', timestamp: '2025-12-02T06:30:00Z', exit_time: '2025-12-02T06:42:00Z', symbol: 'BANKNIFTY24DEC47500CE', side: 'BUY' as const, size: 3, pnl: -3250, bds_at_time: 0.71 },
      { id: 'T-1005', timestamp: '2025-12-03T04:05:00Z', exit_time: '2025-12-03T04:28:00Z', symbol: 'NIFTY24DEC22600CE', side: 'BUY' as const, size: 1, pnl: 2140, bds_at_time: 0.24 },
      { id: 'T-1006', timestamp: '2025-12-03T04:42:00Z', exit_time: '2025-12-03T04:55:00Z', symbol: 'RELIANCE', side: 'BUY' as const, size: 10, pnl: 1680, bds_at_time: 0.38 },
      { id: 'T-1007', timestamp: '2025-12-03T05:20:00Z', exit_time: '2025-12-03T05:48:00Z', symbol: 'BANKNIFTY24DEC48200CE', side: 'SELL' as const, size: 2, pnl: -4210, bds_at_time: 0.84 },
      { id: 'T-1008', timestamp: '2025-12-03T06:05:00Z', exit_time: '2025-12-03T06:20:00Z', symbol: 'NIFTY24DEC22500PE', side: 'BUY' as const, size: 1, pnl: 890, bds_at_time: 0.45 },
      { id: 'T-1009', timestamp: '2025-12-04T04:08:00Z', exit_time: '2025-12-04T04:42:00Z', symbol: 'TCS', side: 'SELL' as const, size: 5, pnl: -1520, bds_at_time: 0.56 },
      { id: 'T-1010', timestamp: '2025-12-04T05:15:00Z', exit_time: '2025-12-04T05:32:00Z', symbol: 'NIFTY24DEC22700CE', side: 'BUY' as const, size: 2, pnl: 5120, bds_at_time: 0.26 },
      { id: 'T-1011', timestamp: '2025-12-04T05:55:00Z', exit_time: '2025-12-04T06:14:00Z', symbol: 'MIDCPNIFTY24DEC', side: 'BUY' as const, size: 4, pnl: 2340, bds_at_time: 0.31 },
      { id: 'T-1012', timestamp: '2025-12-04T06:30:00Z', exit_time: '2025-12-04T06:45:00Z', symbol: 'FINNIFTY24DEC', side: 'SELL' as const, size: 2, pnl: -1890, bds_at_time: 0.68 },
      { id: 'T-1013', timestamp: '2025-12-05T04:10:00Z', exit_time: '2025-12-05T04:38:00Z', symbol: 'NIFTY24DEC22400CE', side: 'BUY' as const, size: 2, pnl: 3450, bds_at_time: 0.29 },
      { id: 'T-1014', timestamp: '2025-12-05T05:02:00Z', exit_time: '2025-12-05T05:18:00Z', symbol: 'BANKNIFTY24DEC47800PE', side: 'BUY' as const, size: 1, pnl: -980, bds_at_time: 0.52 },
      { id: 'T-1015', timestamp: '2025-12-05T05:45:00Z', exit_time: '2025-12-05T06:10:00Z', symbol: 'RELIANCE', side: 'SELL' as const, size: 20, pnl: 3680, bds_at_time: 0.33 },
      { id: 'T-1016', timestamp: '2025-12-06T04:15:00Z', exit_time: '2025-12-06T04:28:00Z', symbol: 'NIFTY24DEC22500CE', side: 'BUY' as const, size: 3, pnl: -2840, bds_at_time: 0.74 },
      { id: 'T-1017', timestamp: '2025-12-06T05:10:00Z', exit_time: '2025-12-06T05:35:00Z', symbol: 'BANKNIFTY24DEC48100CE', side: 'BUY' as const, size: 1, pnl: 1950, bds_at_time: 0.41 },
      { id: 'T-1018', timestamp: '2025-12-06T06:00:00Z', exit_time: '2025-12-06T06:22:00Z', symbol: 'NIFTY24DEC22600PE', side: 'SELL' as const, size: 2, pnl: 2860, bds_at_time: 0.36 },
    ],
    total_count: 18,
    summary: {
      total_pnl: 15560,
      win_count: 11,
      loss_count: 7,
      best_trade: 5120,
      worst_trade: -4210,
    },
  } satisfies TradeHistoryResponse,
}

export function getSampleWorkspaceOverview(preview: ShibuyaSamplePreview = 'core'): DashboardOverview {
  const overview = SAMPLE_WORKSPACE_DATA.overview

  if (preview !== 'reset_pro') {
    return overview
  }

  return {
    ...overview,
    guided_review_included: true,
    guided_review_status: 'invited',
    review_eligibility: true,
    next_action: 'Reset Pro preview: review the first-cycle mandate, then book the guided checkpoint.',
    reports_ready: 2,
    analysis_summary: overview.analysis_summary
      ? {
          ...overview.analysis_summary,
          current_enemy: 'The first-cycle Reset Pro preview is showing overtrading and size creep as the main leaks.',
          next_session_command: 'Reset Pro preview: trade half size until the next append proves the reset is holding.',
          what_to_protect: [
            'Protect the cleanest setup before adding any new risk.',
            'Protect the first-cycle reset from becoming another motivational promise.',
            'Protect capital while the guided checkpoint reviews evidence, not vibes.',
          ],
        }
      : overview.analysis_summary,
    review_summary: {
      eligible: true,
      touchpoint_1_status: 'available',
      touchpoint_2_status: 'locked',
      next_review_type: 'first_cycle_guided_review',
      upcoming_appointment_at: null,
    },
    artifact_descriptors: [
      ...(overview.artifact_descriptors ?? []),
      {
        kind: 'reset_pro_review_packet',
        label: 'Reset Pro Review Packet',
        report_id: 'sample-reset-pro-review',
        snapshot_id: 'sample-upload-2',
        available: true,
      },
    ],
    loyalty_unlock: null,
  }
}

export const SAMPLE_PROFILE_CONTEXT: TraderProfileContext = {
  capital_band: '50k_to_250k_inr',
  monthly_income_band: '25k_to_75k_inr',
  trader_focus: 'retail_fo',
  broker_platform: 'Sample broker',
  primary_instruments: ['nifty_options', 'banknifty_options'],
  trader_mode: 'retail_fn0_struggler',
  completed: true,
}

